services:
  account:
    build:
      context: ./account
      args:
        PORT: ${PORT:-8080}
    container_name: ${APP_NAME:-neblab}-account
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_DATABASE: ${ACCOUNT_DB_NAME}
      DB_NAME: ${ACCOUNT_DB_NAME}
      DB_USER: ${ACCOUNT_DB_USER}
      DB_PASS: ${ACCOUNT_DB_PASS}
      PORT: ${PORT:-8080}
    ports:
      - "${ACCOUNT_PORT:-8080}:${PORT:-8080}"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:latest
    container_name: ${APP_NAME:-neblab}-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASS:-123456}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d


volumes:
  db-data: